name: involucrata
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.11.0+2
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1
  rxdart: ^0.22.0
  flutter_auth_buttons: ^0.5.0
  location: ^2.3.5
  #location: ^1.3.4
  google_maps_flutter: ^0.5.19
  geoflutterfire: ^2.0.3+4
  firebase_storage: ^3.0.0
  flutter_polyline_points: ^0.1.0
  geodesy: ^0.3.0
  web_socket_channel: ^1.0.13
  flutter_launcher_icons: ^0.7.2
  image_picker: ^0.6.0+10
  geocoder: ^0.1.2
  dropdownfield: ^0.0.2
  autocomplete_textfield: ^1.6.6
  flutter_google_pay: ^0.1.4
  multi_image_picker: ^4.3.4
  random_string: ^1.1.0
  geolocator: ^5.0.1
  shared_preferences: ^0.5.3+4
  image: ^2.1.4
  image_picker_saver: ^0.3.0
  cached_network_image: ^1.1.1
  animated_text_kit: ^1.3.1
  video_player: ^0.10.1+3
  album_saver: ^0.0.2
  path_provider: ^1.1.0
  load: ^0.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/splash_icon.png"
  image_path_ios: "assets/splash_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# flutter pub pub run flutter_launcher_icons:main

# The following section is specific to Flutter.
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash_icon.png
    - assets/bau.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
